name: Deploy Gatsby site to Hostinger

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Install dependencies
        run: yarn install
      - name: Build with Gatsby
        env:
          PREFIX_PATHS: 'false'
        run: yarn build
      - name: Set up SSH key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 46.202.156.155
          ssh-port: '65002'
      - name: Rsync Gatsby build to server
        run: rsync -avz -e "ssh -p 65002" --delete ./public/ u494166457@46.202.156.155
